#!/usr/bin/python3

import argparse
import sys

from common import ChangesetStore


parser = argparse.ArgumentParser(
    description='Print GitHub PR belonging to given commit.')
parser.add_argument('commit', type=str, help='git commit hash')
parser.add_argument('-r', '--refresh', action='store_true',
                    help='always fetch from server (do not use cache)')
args = parser.parse_args()


s = ChangesetStore(text=True)
s.load([args.commit], args.refresh)
try:
    out = s[args.commit]
except KeyError:
    sys.exit(1)
else:
    print(out)
