#!/bin/bash
#
# Build reference docs for each configured project and its version series.

set -e

SCRIPT_DIR=$(dirname $(readlink -f $0))
DATA_FILE=$SCRIPT_DIR/_data/projects.yml
DEST_DIR=$SCRIPT_DIR/docs

yq() {
    command yq -ot "$1" $DATA_FILE
}

build() {
    local name=$1
    local query=".[] | select(.name == \"$name\")"
    local repo_url=$(yq "${query}.repourl")
    local latest=$(yq "${query}.stable[0]")
    local repo_dir=$SCRIPT_DIR/_build/$name
    local src_path dst_path

    [ -d "$repo_dir/.git" ] || git clone --bare $repo_url $repo_dir/.git

    for series in $(yq "${query}.docs.[].series"); do
        local tree_query="${query}.docs.[] | select(.series == \"$series\")"
        local tree_dir=${repo_dir}/${name}-${series}
        local dest_dir=$DEST_DIR/$series
        local build=$(yq "${tree_query}.build")

        [ "$build" == "null" ] && continue
        [ -d "$tree_dir" ] || git -C $repo_dir worktree add $tree_dir

        mkdir -p $dest_dir
        DESTDIR=$dest_dir bash -c "cd $tree_dir && $build"
    done

    # Create latest "alias"
    cp -r $DEST_DIR/$latest $DEST_DIR/latest
}

for project in $(yq ".[].name"); do
    build $project
done
